[package]
name = "beads-and-threads"
version = "1.1.0"
authors = ["Serge Barinov <bool.rus@gmail.com>"]
edition = "2018"

[dependencies]
iced = {version = '*', features=["svg"]}
iced_native = '*'
iced_wgpu = '*'
quick-csv = "*"
