[package]
name = "beads-and-threads"
version = "0.1.0"
authors = ["Баринов Сергей Владимирович <SVBarinov.SBT@sberbank.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
